### ISSUE TITLE
1.Settings component

### ISSUE THREAD

**Issue by Zaki5581** [Zaki5581/capstone-project#1]
## Value proposition

**As a** user 
**I want to** plan my workout for a week.
**so that** i have my weekly workout stored.

## Description

 
<img width="423" alt="Bildschirmfoto 2022-06-23 um 19 27 57" src="https://user-images.githubusercontent.com/92207171/175359107-4a045d0b-f4c9-483c-ab51-87b8e9924307.png">

## Acceptance criteria

- [ ] the day workout should be displayed in as a  list. 
- [ ] the inputs should be controlled.
- [ ] the ability to store more than one workout.

## Complexity

 Medium 

## Tasks

- [ ] Create branch.
- [ ] Setup storybook for settings component.
- [ ] Write specs for the Settings component
- [ ] Getting data from the form.
- [ ] After clicking the 'set workout' button, the workout should be displayed as an unordered list.
- [ ] Add TodoForm to the App component.
- [ ] style the component, and display the workouts in a list.
