### ISSUE TITLE
setting trainingday

### ISSUE THREAD

**Issue by Zaki5581** [Zaki5581/capstone-project#10]
## Value proposition

**As a** user,
**I want to** to set a date to my workout
**so that** i can plan how many days i want recover after a workout 

## Description

<img width="526" alt="Bildschirmfoto 2022-07-14 um 15 10 08" src="https://user-images.githubusercontent.com/92207171/178990168-dc76e5e9-d2d4-4e11-a4a4-6468999b9e6b.png">

## Acceptance criteria

- [ ]every workout should appears with a date.

## Complexity

Small

## Tasks

- [ ] Create branch
- [ ] implement input type "date
- [ ] set the date state
- [ ] display the chosen date
