### ISSUE TITLE
Nutrition watch

### ISSUE THREAD

**Issue by Zaki5581** [Zaki5581/capstone-project#11]
## Value proposition

**As a** user,
**I want to** I want to track my daily intake nutrients
**so that** i have an overview how i can organize my next meals.

## Description
<img width="377" alt="Bildschirmfoto 2022-07-15 um 14 45 28" src="https://user-images.githubusercontent.com/92207171/179226989-20471491-f1c0-4461-b7fa-57837e3429a1.png">

## Acceptance criteria

- [ ] the bars in the chart should show the average amount of nutrients(1 is 100%)
- [ ] the bars height should change every time new intakes are added.

## Complexity

  Medium 

## Tasks

- [ ] Create branch
- [ ] install chart.js
- [ ] get the right input values needed.
- [ ] get everything in shape and place.
