### ISSUE TITLE
the home component

### ISSUE THREAD

**Issue by Zaki5581** [Zaki5581/capstone-project#2]
## Value proposition

**As a** user,
**I want to navigate between four components.
**so that  i manage my workout and nutrition, and an overview about my statistics.

## Description

<img width="423" alt="Bildschirmfoto 2022-06-23 um 11 46 39" src="https://user-images.githubusercontent.com/92207171/175273228-0ef2df55-d5b7-4749-8050-8f5bfb580c5e.png">

## Acceptance criteria

- [ ] the Home button should lead to this component. 

## Complexity

Small | Medium | Large

## Tasks

- [ ] Create branch.
- [ ] Setup Storybook for the home component.
- [ ] Create four buttons that describe the four components of the app.
- [ ] Create a home button that appears in all components. 
- [ ] Style the home component.

**Comment by ahohnsen** [comment]
Hey Zakaria,

As already discussed, it would be better to implement this user story later on. I am looking forward to your new user stories :)
