### ISSUE TITLE
Adding new exercises to db.js

### ISSUE THREAD

**Issue by Zaki5581** [Zaki5581/capstone-project#4]
## Value proposition

**As a** user,
**I want to** have enough exercises for each body part.
**so that** i have a better variety of exercises.

## Acceptance criteria

- [ ]the exercises should match the body part.

## Complexity

Medium

## Tasks

- [ ] Add new exercises in db.js
- [ ] the exercises should be reachable from the setting component.
- [ ] Sort the exercises after clicking a body part.
- [ ]
