### ISSUE TITLE
Setting the nutrition component

### ISSUE THREAD

**Issue by Zaki5581** [Zaki5581/capstone-project#8]
## Value proposition

**As a** user,
**I want to be able to track my Nutrients.
**so that i have an overview of the amount of nutrients i should take, and be able to make a comparison to how much i really taken.

## Description

<img width="762" alt="Bildschirmfoto 2022-07-09 um 12 32 30" src="https://user-images.githubusercontent.com/92207171/178102072-13dc04c5-b9e2-41af-8f0b-dc07f903a24f.png">

## Acceptance criteria

- [ ]the goal and taken nutrients should be displayed after a button click in different areas in the screen
- [ ]setting the home component also ,so that the user should be navigate between training and nutrition component.

## Complexity

 Medium 

## Tasks

- [ ] Create branch
- [ ] Create the home component
- [ ] create the nutrition component
- [ ] implement routing so i can navigate between the two components

**Comment by JessicaLoers** [comment]
**Hello @Zaki5581** 👋
Nice ideas, but I've some or some more 😁 suggestions you could think about.
Please understand that my detailed comments are intended to support you in the process of User Story, Pull Request, Quality Assurance. If the user story is small, well thought out and planned, the other steps will flow more smoothly - like butter 🧈

**Markdown Formatting issues**
- Value proposition: `**I want to**` - or choose `add bold  text` in the toolbar above the textarea
- Acceptance criteria: `- [ ] Something to to` - or choose `add task list` in the toolbar above the textarea

**User Story Titel**
- Please, keep in mind: user stories are created from the user's point of view. For this reason, I would recommend the following title, for example: `Log the users nutrient intake`

**Value proposition**
I suggest to split this into two User Stories. 

First US is about adding the single nutrient intake:
- **I want to** log my nutrient intake
- **So that I** have a list of my las nutrient intake

Second US is about compare the nutrient intake - perhaps with a progress bar or something similar 
- **I want to** log my nutrient intake by days _(or week, or what ever you want)_
- **So that I** that I have a comparable history of my nutrient intake

**Description**
- Please think about a different label for your button 
- I'm a bit confused - what are the rectangles with the white outline 🫣
- Where's the input fields/form 

**Acceptance criteria**
- first things first, where/how can I add my nutrient entries?
- what exactly can I add? Is there a date picker or something?
- what happens after I have made my entry?
- ...  and so on.

**Tasks**
If you implement my suggestions, you should think again about your tasks.
